fireman learn oop
burlakvo/masa-test pull request #5
Opened 2019-09-17 15:59 UTC by burlakvo

2019-09-17 16:10 UTC, Kronenberg commented
отпишешь как закончишь :) если есть вопросы по ревью отпиши в лс в телеграмме

2019-09-17 16:20 UTC, Kronenberg requested changes

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +		this.geo = document.getElementById("street");
Инициализировать такие вещи в коснтрукторе плохая практика :) используй для этого например метод инит внутри уже самого класса

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +	constructor (i) {
тоже самое перенеси подобные вещи из конструктора в метод инит (инициализация дефолтных значений - например )

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +		let buildingNum = buildings.length;
почему не константы?

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +		let t = this;
используй метод bind  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind 
подобной трик использовали в 2005 :)

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +		setInterval(function() {t.streetWatch()}, 50);
не понял зачем оборачивать в функцию или если сильно надо то можно обернуть в arrow function если у тебя проблема scope https://www.freecodecamp.org/news/an-introduction-to-scope-in-javascript-cbd957022652/

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +		buildingsInFire.forEach(function (item, index) {
user arrow function

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +			return;
попробуй найти и использовать другую логику если хочешь оборвать функцию

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +	var fireman = new Fireman;
в одном месте ты используешь лэты а тут вар :) будь постоянен

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +		let t = this;
тоже самое если проблема в скоуп используй байнд

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +		let t = this;
тоже самое

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +var fire;
let?

2019-09-17 16:20 UTC, Kronenberg commented on city_in_fire/action.js
> +	var street = new Street;
const?

2019-09-18 05:42 UTC, burlakvo commented on city_in_fire/action.js
> +		this.geo = document.getElementById("street");
Переделал на передачу id в конструктор во время инициализации класса

2019-09-18 05:58 UTC, burlakvo commented on city_in_fire/action.js
> +		let buildingNum = buildings.length;
Почти каждый раз массив "домов, которые не горят" будет другой, поэтому не делал как константу

2019-09-18 07:02 UTC, burlakvo commented on city_in_fire/action.js
> +		setInterval(function() {t.streetWatch()}, 50);
Нужно было комментировать, потому что уже сам не помню))

2019-09-18 09:48 UTC, burlakvo commented on city_in_fire/action.js
> +		buildingsInFire.forEach(function (item, index) {
Сначала переделал с использованием bind(). Потом начал делать arrow function, а с ней оказалось, что bind() не нужен. Зато разобрался с bind() =)

2019-09-18 17:28 UTC, merged